import {
  LayoutDashboard,
  BarChart3,
  ClipboardList,
  Calendar,
  Filter,
  Upload,
  Download,
  Users,
  Settings,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  TrendingUp,
  TrendingDown,
  Minus,
  PieChart,
  FileText,
  Search,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  X,
  Check,
  Bell,
  Home,
  Building,
  Zap,
  Award,
  Palette,
  Code,
  HelpCircle,
  GraduationCap,
  Sparkles,
  Layers,
  Sun,
  Moon,
  Monitor,
  Network,
  LogOut,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from './iconTypes';

/**
 * Central Registry for UBITS Icon System.
 * Maps semantic UBITS names to provider icons (currently Lucide fallback).
 *
 * NOTE: This is the only file where direct icon provider imports are allowed.
 * To migrate to Iconly, replace the Lucide imports here with Iconly TSX/SVG components.
 */
export const iconRegistry: Record<IconName, LucideIcon | React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  dashboard: LayoutDashboard,
  analytics: BarChart3,
  survey: ClipboardList,
  calendar: Calendar,
  filter: Filter,
  upload: Upload,
  download: Download,
  users: Users,
  settings: Settings,
  warning: AlertTriangle,
  success: CheckCircle2,
  error: XCircle,
  info: Info,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  neutral: Minus,
  chart: PieChart,
  file: FileText,
  search: Search,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  close: X,
  check: Check,
  notification: Bell,
  home: Home,
  building: Building,
  bolt: Zap,
  award: Award,
  palette: Palette,
  code: Code,
  help: HelpCircle,
  graduation: GraduationCap,
  sparkles: Sparkles,
  layers: Layers,
  sun: Sun,
  moon: Moon,
  vacancies: Monitor,
  templates: Network,
  logout: LogOut,
};

/**
 * Fallback icon to use when a requested name is missing from the registry.
 */
export const IconFallback = AlertTriangle;
